JavaScript capstone project - Your API-based webapp
ntzwilly/JS-capstone pull request #31
Opened 2021-08-14 15:18 UTC by ntzwilly

## Description

- Use JavaScript to make websites dynamic
- Use callbacks and promises to consume Two APIs: Meals DB & Involvement API
- Use Webpack
- Write units tests for a JavaScript app.
- Follow Gitflow.
- Send and receive data from an API.
- Use API documentation.
- Perform a code review for a team member.

2021-08-14 16:38 UTC, ZawadiSumba66 requested changes
Hi Team 😃 , 

Good job so far on this project 👏 👏 
However, there are some issues that you still need to work on to go to the next step but you are almost there! 💪 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 16:38 UTC, ZawadiSumba66 commented on src/comments.js
> +export const displayComments = (items) => {
- [ ] When a user first adds a comment to the popup there is an undefined word appears and the comments count does not increase. It's only after one closes and reopens the popup again that the undefined disappears and the comments count increases. 
- [ ] There is also another issue where if create another comment in the same popup the previous one disappears.
- [ ] Check out this[ loom](https://www.loom.com/share/7f35ba213980400b988346721535828e) video to further demonstrate your app behavior.

2021-08-14 16:38 UTC, ZawadiSumba66 commented on src/utils.js
> +const getCommentsCount = (comments) => comments.length || 0;
- [ ] As from the requirements given, you need to create a specific function to calculate counter numbers on each page i.e for the comments and the items; even if the API provides that information. You can write the function in such a way that you loop through the data fetched and then display the count.

2021-08-14 16:38 UTC, ZawadiSumba66 commented on src/index.js
> +async function mealCounter() {
- [ ] Ii seems that you have forgotten to apply the ES6 syntax on some function declarations i.e the use of arrow functions here. Kindly correct this and all the other files/areas where you had missed this.

2021-08-14 20:30 UTC, ntzwilly commented on src/comments.js
> +export const displayComments = (items) => {
The issues are now fixed

2021-08-14 20:31 UTC, ntzwilly commented on src/utils.js
> +const getCommentsCount = (comments) => comments.length || 0;
Thank you, I have created a function

2021-08-14 20:32 UTC, ntzwilly commented on src/index.js
> +async function mealCounter() {
I am now using ES6

2021-08-14 21:09 UTC, dasileker requested changes
**### Hi @ntzwilly,** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 21:09 UTC, dasileker commented on README.md
> +
- [ ] Th live demo is different from the one in the dev branch, please update it.

2021-08-14 21:09 UTC, dasileker commented on src/index.js
> +        e.preventDefault();
- [ ] The Likes are not working, I do see that the previous TSE mentioned this but still not working see screenshot 👇

https://user-images.githubusercontent.com/61562626/129460027-1aa2a068-f216-48d0-969a-10b8e865205e.mp4

2021-08-15 04:45 UTC, hemant-soni-vst-au4 approved these changes
Hi @ntzwilly and @Adewunmi97, 

Good work on making the requested changes. 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 00:42 UTC, merged